### ISSUE TITLE
Explanation of (1.3)

### ISSUE THREAD

**Issue by denkorzh** [diefimov/MTH594_MachineLearning#1]
Page 14 of [lectures](https://github.com/diefimov/MTH594_MachineLearning/blob/master/lectures/MTH594_Lectures_DmitryEfimov.pdf), formula (1.3).

Possibly it would be useful to explain that we do not consider $p( x^{\( i \)} | \theta )$ because actually it equals $p( x^{\( i \)} )$ since $x^{\( i \)}$ doesn't depend on $\theta$ and therefore this term has no sense in the problem of maximization

**Comment by diefimov** [comment]
Corrected.
