### ISSUE TITLE
Parameters in Gaussian discriminant analysis

### ISSUE THREAD

**Issue by denkorzh** [diefimov/MTH594_MachineLearning#2]
Section 4.3 (page 38)

When we calculate the number of parameters for the case of 2 classes and 2 features, we forget that \Sigma_0 and \Sigma_1 are symmetrical. So, the real number of parameters equals 1+2+2+3+3 = 11 (for \phi, \mu_0, \mu_1, \Sigma_0, \Sigma_1 respectively).

**Comment by diefimov** [comment]
Corrected.
