### ISSUE TITLE
Set of paramters for optimization

### ISSUE THREAD

**Issue by denkorzh** [diefimov/MTH594_MachineLearning#5]
Section 6.1, page 64.

When we formulate the first optimization problems the margin \gamma wouldn't belong to the set we solve the problem over. The same concerns the equivalent (second) one.

**Comment by diefimov** [comment]
I agree with the first comment as we maximize \gamma. But for the second optimization problem we maximize \hat{\gamma}/||w|| as a function of \hat{\gamma}, w and b.
