### ISSUE TITLE
Incorrect place of superscript

### ISSUE THREAD

**Issue by denkorzh** [diefimov/MTH594_MachineLearning#6]
Section 6.4, page 69.

The superscript (i) should belong to \phi(x), not x

**Comment by diefimov** [comment]
In fact, these two notations are equivalent: \phi(x^(i)) means transformation of i-th training example; \phi(x)^(i) means transformation of all training examples and taking i-th training example in the new space. But I agree with you, it is better to have unified notations. Corrected.
